import localFont from 'next/font/local'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Menu from "@/components/ui/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazir = localFont({
   src: [
      {
         path: "../../public/fonts/Vazir-Thin.ttf",
         weight: "400",
         style: "normal",
      },
   ],

   variable: "--vazir",
   display: "swap",
   preload: true,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className={`${vazir.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Navbar />
         <Menu />
         {children}
      </body>
    </html>
  );
}
